### ISSUE TITLE
not able to download game data & play

### ISSUE THREAD

**Issue by Dkra** [rwv/chinese-dos-games-web#1]
After running the downloading command
`git submodule update --recursive --remote && git submodule update --recursive --remote && python3 ./static/games/download_data.py`
there's **no game data** download to project /static/games/bin folder

Can't play without game data.

**Comment by rwv** [comment]
what's the output of `git submodule update --recursive --remote && git submodule update --recursive --remote && python3 ./static/games/download_data.py`?

**Comment by Dkra** [comment]
After clone this project,
First time run the command
`git submodule update --recursive --remote && git submodule update --recursive --remote && python3 ./static/games/download_data.py`
will result  as below image
![image](https://user-images.githubusercontent.com/5117252/46579986-1433d080-ca4e-11e8-8bc4-09b4cdef66f7.png)

To solve this,  I copy the files **download_data.py & games.json** from your source projects 
https://github.com/rwv/chinese-dos-games

Then run the first git command again, **there's no error message, and no game downloaded to the destination folder**,  result like this
![image](https://user-images.githubusercontent.com/5117252/46580010-a76d0600-ca4e-11e8-8339-5af83e9b34d6.png)

Please let me know if I doing the wrong way, thanks!

**Comment by Dkra** [comment]
By the way, after running the command `python3 app.py`, open the browser select the game will be result like this

![image](https://user-images.githubusercontent.com/5117252/46580053-a7b9d100-ca4f-11e8-84af-fcb8ca9f15a3.png)

**Comment by Guadeloupu** [comment]
change      chinese-dos-games-web/static/games/download_data.py      

PREFIX = "https://dos.zczc.cz/static/gamedates/"  to    

PREFIX = "https://dos.zczc.cz/static/games/bin/"  

ok！
下载文件里的目录错了！！！

**Comment by rwv** [comment]
@Dkra Indeed, the command `git submodule update --recursive --remote && git submodule update --recursive --remote && python3 ./static/games/download_data.py` does not initiate the submodule correctly. See also https://git-scm.com/book/en/v2/Git-Tools-Submodules

**Comment by rwv** [comment]
@Dkra Is there any game files in the folder `static/games/bin` after running `download_data.py`?

**Comment by Guadeloupu** [comment]
> @Guadeloupu
> 脚本中的目录一直是这个啊 https://github.com/rwv/chinese-dos-games/blob/master/download_data.py
> The path in the python script has already been that path.

我直接git clone这个源码的话，static里的games文件夹是空的，然后又用zip单独下载了games文件夹，然后也出现这个错误，把path路径改了以后就好了

**Comment by rwv** [comment]
发现了应该是 git submodule 一直在停留在 https://github.com/rwv/chinese-dos-games/commit/d781c7ac19e80197032bb26d77de0e1018a62772 导致的

**Comment by rwv** [comment]
@Dkra @Guadeloupu try `git submodule update --init --recursive --remote && python3 ./static/games/download_data.py` under the root directory.

**Comment by Dkra** [comment]
@rwv It works like a charm! thanks!
