### ISSUE TITLE
存档莫名丢失……

### ISSUE THREAD

**Issue by Fredpata** [rwv/chinese-dos-games-web#10]
**bug 描述**
bug 的描述
玩过三国志英杰传 仙剑 皇帝
之前好好的，今天只有皇帝的存档还在。英杰传和仙剑的存档都不见了，回到了初始第一次玩的状态
**如何重现**
如何重现这个 bug
未知
**预期情况**
你预期的正常情况
存档正常读取
**截图**
bug 的截图

**系统环境**
操作系统： OSX 10.13.6
浏览器：Chrome Version 71.0.3578.98 (Official Build) (64-bit)
游戏：三国英杰传 仙剑 皇帝

**Comment by Fredpata** [comment]
<img width="1212" alt="1" src="https://user-images.githubusercontent.com/1464774/50638255-0a136680-0f98-11e9-9bb0-2d3b4caa8349.png">
<img width="1276" alt="2" src="https://user-images.githubusercontent.com/1464774/50638256-0b449380-0f98-11e9-98e7-f10c2c56c962.png">
这样？

**Comment by rwv** [comment]
看上去的确被删掉了，我也没法在我这复现，只能等待后续存档导出功能的开发。

**Comment by rwv** [comment]
顺便这是localhost？可能因为Chrome对localhost的indexeddb清理了？有在localhost:5000上跑过其他程序吗

**Comment by Fredpata** [comment]
> 顺便这是localhost？可能因为Chrome对localhost的indexeddb清理了？有在localhost:5000上跑过其他程序吗

记起来了……好像跑过 pyspider……这个游戏的默认端口在哪里改，我去查查

**Comment by rwv** [comment]
`app.py` 最后一行，`app.run(host='0.0.0.0', port=80)`

**Comment by rwv** [comment]
https://developers.google.com/web/fundamentals/instant-and-offline/web-storage/offline-for-pwa 顺便这里介绍了 Chrome 中 indexeddb 的容量限制和删除策略
