### ISSUE TITLE
使用时候 提示Failed to download game data! 

### ISSUE THREAD

**Issue by oldiy** [rwv/chinese-dos-games-web#14]
进入vi download_data.py 查看 PREFIX = “https://dos.zczc.cz/static/bin/” 也是这个目录
但是就是无法进入游戏

![](https://odcn.top/wp-content/uploads/2019/02/12121212-1024x679.jpg)

执行git submodule update --init --recursive --remote && python3 ./static/games/download_data.py 命令后，就如下图，显示正在downloading，但是bin里没有任何文件
![](https://odcn.top/wp-content/uploads/2019/02/TIM%E6%88%AA%E5%9B%BE20190212101614.jpg)

**Comment by oldiy** [comment]
目录bin下也没有任何文件

**Comment by longminxiang** [comment]
在download_data.py里加上

**Comment by rwv** [comment]
@oldiy 从您博客看来已经解决了？先关闭了，如有问题请您打开。
