### ISSUE TITLE
'git submodule update.....' leads to fatal error

### ISSUE THREAD

**Issue by ghost** [rwv/chinese-dos-games-web#15]
Widows:

git submodule update --init --recursive --remote && python3 ./static/games/download_data.py
git bash this command , it led to :
fatal: not a git repository (or any of the parent directories): .git

for your help sincerely :D

**Comment by rwv** [comment]
Which directory are you under when executing the command?

**Comment by tea1111980** [comment]
我也有同样的问题。执行这个命令的时候，我在 /app# 目录下，对吧？
我也切换到 / 目录下执行，一样的报这个错。
注：我不是原贴作者
