### ISSUE TITLE
https 反向代理 游戏界面 Get 404

### ISSUE THREAD

**Issue by summitn** [rwv/chinese-dos-games-web#17]
![](https://img.waypons.com/imgs/2019/11/45717c13ba8aa1aa.png)

问下这个怎么解决呢,是不是哪里要开启ssl?
不走代理内网http ip 端口 的形式访问是可以玩的
我用的是docker版 然后用了https的反向代理

**Comment by rwv** [comment]
没有下载游戏文件？

**Comment by summitn** [comment]
有下载游戏,bin文件夹里有对应的游戏文件

不走代理内网http ip 端口 的形式访问是可以玩的
![](https://img.waypons.com/imgs/2019/11/2a827dff592e458d.png)

**Comment by summitn** [comment]
我刚才试了下 应该是代理的问题 和 https 应该没有关系

能帮我看下这个代理配置有什么问题么

```apache
#PROXY-START/
<IfModule mod_proxy.c>
    ProxyRequests Off
    SSLProxyEngine on
    ProxyPass / http://127.0.0.1:8094/
    ProxyPassReverse / http://127.0.0.1:8094/
    </IfModule>
#PROXY-END/
```

**Comment by summitn** [comment]
换了iis的反向代理也不行 应是反向代理导致载不到静态资源..

**Comment by rwv** [comment]
看一下内网http ip 端口的时候访问开发者工具页面

**Comment by summitn** [comment]
![](https://img.waypons.com/imgs/2019/11/94b5b7636ec0a291.png)

空白的..

**Comment by qunlovehe** [comment]
反代，我可以加载，但是在加载游戏的界面是提示失败并且服务端显示301了。
