### ISSUE TITLE
求助 无法启动

### ISSUE THREAD

**Issue by chinapao123** [rwv/chinese-dos-games-web#2]
您好，很喜欢您的项目，按照readme进行操作，最后一步$ python3 app.py后 服务器提示
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 216-142-719

访问服务器ip或者ip:5000均无法访问，请教有没有更详细的步骤？

**Comment by rwv** [comment]
绑定在了 `127.0.0.1` 上，需要修改为`0.0.0.0`
修改 `app.py` 最后为 `app.run(host='0.0.0.0')`
