### ISSUE TITLE
請問最新版的源碼在那?

### ISSUE THREAD

**Issue by mcdullmedia** [rwv/chinese-dos-games-web#22]
我 clone 下來的與 https://dos.zczc.cz/ 中很多功能不一樣.
另外請問安卓可以使用手柄嗎?

**Comment by rwv** [comment]
手柄功能尚未添加，应该可以使用 WebHID 添加，目前的网站是纯前端的，您可以在 npm 上的 dos.zczc.cz_vue 上找到。

**Comment by rwv** [comment]
https://www.npmjs.com/package/dos.zczc.cz_vue
