### ISSUE TITLE
游戏无法下载

### ISSUE THREAD

**Issue by dengyull** [rwv/chinese-dos-games-web#23]
下载下来的全是3k多的文件，游戏本体无法下载。

**Comment by LateSong** [comment]
下载链接已被弃用，可以进行更新了。
PREFIX=' https://dos_bin.zczc.cz/'

**Comment by LateSong** [comment]
![image](https://user-images.githubusercontent.com/16833302/116273639-8313d900-a7b4-11eb-98ae-b95636d3b90a.png)
测试效果

**Comment by dengyull** [comment]
是否存有新的下载链接·呢？dos_bin.zczc.cz访问是403 Forbidden

**Comment by rwv** [comment]
https://dos_bin.zczc.cz 自身就是403的，现在已修复了。
