### ISSUE TITLE
代码和网站还是有些差别的，望提交到最新哈

### ISSUE THREAD

**Issue by nickdanes** [rwv/chinese-dos-games-web#3]
首页里的游戏是完全遍历games.json的，另外也没有游戏列表链接哈，（和网站上相比）

**Comment by Hwgin** [comment]
对，一开始我还以为是我配置的问题，发现首页不一样，所有游戏都显示在首页，另外也没有搜索框2018/11/2

**Comment by lsweicheng** [comment]
同求更新的跟主站一样,😆

**Comment by rwv** [comment]
已修复，应该一样了。
