### ISSUE TITLE
设计一下保存游戏进度的方法

### ISSUE THREAD

**Issue by ColdCodeHah** [rwv/chinese-dos-games-web#7]
新增用户登录并保存游戏进度怎么样

**Comment by ColdCodeHah** [comment]
新增用户登录并保存游戏进度怎么样

**Comment by rwv** [comment]
在清单上，但实现时间未定。

**Comment by philiptzou** [comment]
其实可以让用户下载indexeddb再上传：https://gist.github.com/loilo/ed43739361ec718129a15ae5d531095b

**Comment by rwv** [comment]
fixed
