### ISSUE TITLE
使用过程中的几个问题

### ISSUE THREAD

**Issue by Fredpata** [rwv/chinese-dos-games-web#9]
1、fork 还是直接下载，得到的game 文件下都是空的，此时只能从老的https://github.com/rwv/chinese-dos-games 把 download_data.py个 games.json下下来复制到game 文件夹。需要修正
2、运行游戏下载脚本，因为上面那个问题，download_data.py里的地址需要修正：
change chinese-dos-games-web/static/games/download_data.py
PREFIX = "https://dos.zczc.cz/static/gamedates/" to
PREFIX = "https://dos.zczc.cz/static/games/bin/"
https://github.com/rwv/chinese-dos-games-web/issues/1#issuecomment-429195557
3、下载的游戏数量一下子过多了……600多MB……需要提醒
4、玩游戏的时候……注意还是网页全屏好，把鼠标指针焦点要注意下。

**Comment by rwv** [comment]
1. 参见 README.MD，需要执行 `git submodule update --init --recursive --remote && python3 ./static/games/download_data.py`
2.  `download_data.py` 不是已经更新到 "https://dos.zczc.cz/static/games/bin/" 吗？ https://github.com/rwv/chinese-dos-games/blob/master/download_data.py#L12
3. 一共是 36G 游戏大小

**Comment by Fredpata** [comment]
> 1. 参见 README.MD，需要执行 `git submodule update --init --recursive --remote && python3 ./static/games/download_data.py`
> 2. `download_data.py` 不是已经更新到 "https://dos.zczc.cz/static/games/bin/" 吗？ https://github.com/rwv/chinese-dos-games/blob/master/download_data.py#L12
> 3. 一共是 36G 游戏大小

习惯性的从games @ d781c7a进了 可以考虑这里也更新下
https://github.com/rwv/chinese-dos-games/blob/d781c7ac19e80197032bb26d77de0e1018a62772/download_data.py

**Comment by rwv** [comment]
不准备更新，因为 `chinese-dos-games` 中的 `games.json` 是包含游戏下载文件的 sha256，即使将prefix更新正确，sha256也不一定是最新的，所以不更新。

**Comment by Fredpata** [comment]
> 不准备更新，因为 `chinese-dos-games` 中的 `games.json` 是包含游戏下载文件的 sha256，即使将prefix更新正确，sha256也不一定是最新的，所以不更新。

其实我觉的可以把完整的 games.json单独列出，注明下，然后其他人想下载哪几个 就自己去修改这个文件。

**Comment by rwv** [comment]
目前用户可以自己去编辑 `static/games/games.json`，来进行自定义下载，可以更新一下README？
